import { UserAdmin } from "@/types/Admin";

export const adminUsers: UserAdmin[] = [
  {
    id: "1",
    name: "Alex Johnson",
    age: 23,
    gender: "female",
    matchScore: 95,
    phone: "+12 345 6789 0",
    email: "alex.johnson@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    bio: "Love music and art...",
    status: "approved",
  },
  {
    id: "2",
    name: "Maria Garcia",
    age: 28,
    gender: "female",
    matchScore: 92,
    phone: "+12 345 6789 1",
    email: "maria.garcia@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    bio: "Traveler and foodie.",
    status: "pending",
  },
  {
    id: "3",
    name: "John Smith",
    age: 30,
    gender: "male",
    matchScore: 88,
    phone: "+12 345 6789 2",
    email: "john.smith@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    bio: "Sports enthusiast.",
    status: "rejected",
  },
  {
    id: "4",
    name: "Emily Davis",
    age: 25,
    gender: "female",
    matchScore: 90,
    phone: "+12 345 6789 3",
    email: "emily.davis@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    bio: "Book lover and writer.",
    status: "approved",
  },
  {
    id: "5",
    name: "Michael Brown",
    age: 27,
    gender: "male",
    matchScore: 85,
    phone: "+12 345 6789 4",
    email: "michael.brown@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    bio: "Tech geek.",
    status: "pending",
  },
  {
    id: "6",
    name: "Sophia Wilson",
    age: 24,
    gender: "female",
    matchScore: 93,
    phone: "+12 345 6789 5",
    email: "sophia.wilson@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    bio: "Yoga and wellness.",
    status: "rejected",
  },
  {
    id: "7",
    name: "David Martinez",
    age: 29,
    gender: "male",
    matchScore: 87,
    phone: "+12 345 6789 6",
    email: "david.martinez@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    bio: "Music producer.",
    status: "approved",
  },
  {
    id: "8",
    name: "Olivia Anderson",
    age: 26,
    gender: "female",
    matchScore: 91,
    phone: "+12 345 6789 7",
    email: "olivia.anderson@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    bio: "Fashion designer.",
    status: "pending",
  },
  {
    id: "9",
    name: "James Lee",
    age: 31,
    gender: "male",
    matchScore: 89,
    phone: "+12 345 6789 8",
    email: "james.lee@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    bio: "Photographer.",
    status: "rejected",
  },
  {
    id: "10",
    name: "Isabella Thomas",
    age: 22,
    gender: "female",
    matchScore: 94,
    phone: "+12 345 6789 9",
    email: "isabella.thomas@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    bio: "Artist and painter.",
    status: "approved",
  },
  {
    id: "11",
    name: "Benjamin Taylor",
    age: 28,
    gender: "male",
    matchScore: 86,
    phone: "+12 345 6789 10",
    email: "benjamin.taylor@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    bio: "Chef and foodie.",
    status: "pending",
  },
  {
    id: "12",
    name: "Mia Moore",
    age: 27,
    gender: "female",
    matchScore: 92,
    phone: "+12 345 6789 11",
    email: "mia.moore@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    bio: "Nature lover.",
    status: "rejected",
  },
  {
    id: "13",
    name: "William Jackson",
    age: 32,
    gender: "male",
    matchScore: 90,
    phone: "+12 345 6789 12",
    email: "william.jackson@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    bio: "Entrepreneur.",
    status: "approved",
  },
  {
    id: "14",
    name: "Charlotte White",
    age: 25,
    gender: "female",
    matchScore: 93,
    phone: "+12 345 6789 13",
    email: "charlotte.white@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    bio: "Dancer.",
    status: "pending",
  },
  {
    id: "15",
    name: "Elijah Harris",
    age: 29,
    gender: "male",
    matchScore: 88,
    phone: "+12 345 6789 14",
    email: "elijah.harris@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    bio: "Fitness coach.",
    status: "rejected",
  },
  {
    id: "16",
    name: "Amelia Martin",
    age: 26,
    gender: "female",
    matchScore: 91,
    phone: "+12 345 6789 15",
    email: "amelia.martin@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    bio: "Photographer.",
    status: "approved",
  },
  {
    id: "17",
    name: "Logan Thompson",
    age: 30,
    gender: "male",
    matchScore: 87,
    phone: "+12 345 6789 16",
    email: "logan.thompson@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    bio: "Gamer and streamer.",
    status: "pending",
  },
  {
    id: "18",
    name: "Harper Garcia",
    age: 24,
    gender: "female",
    matchScore: 92,
    phone: "+12 345 6789 17",
    email: "harper.garcia@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    bio: "Animal lover.",
    status: "rejected",
  },
  {
    id: "19",
    name: "Alexander Clark",
    age: 28,
    gender: "male",
    matchScore: 89,
    phone: "+12 345 6789 18",
    email: "alexander.clark@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    bio: "Cyclist.",
    status: "approved",
  },
  {
    id: "20",
    name: "Evelyn Lewis",
    age: 25,
    gender: "female",
    matchScore: 94,
    phone: "+12 345 6789 19",
    email: "evelyn.lewis@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    bio: "Gardener.",
    status: "pending",
  },
  {
    id: "21",
    name: "Daniel Walker",
    age: 27,
    gender: "male",
    matchScore: 86,
    phone: "+12 345 6789 20",
    email: "daniel.walker@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    bio: "Movie buff.",
    status: "rejected",
  },
  {
    id: "22",
    name: "Abigail Hall",
    age: 23,
    gender: "female",
    matchScore: 93,
    phone: "+12 345 6789 21",
    email: "abigail.hall@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    bio: "Baker.",
    status: "approved",
  },
  {
    id: "23",
    name: "Matthew Allen",
    age: 29,
    gender: "male",
    matchScore: 88,
    phone: "+12 345 6789 22",
    email: "matthew.allen@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    bio: "Hiker.",
    status: "pending",
  },
  {
    id: "24",
    name: "Ella Young",
    age: 26,
    gender: "female",
    matchScore: 91,
    phone: "+12 345 6789 23",
    email: "ella.young@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
    bio: "Runner.",
    status: "rejected",
  },
  {
    id: "25",
    name: "Jackson King",
    age: 31,
    gender: "male",
    matchScore: 90,
    phone: "+12 345 6789 24",
    email: "jackson.king@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    bio: "Poet.",
    status: "approved",
  },
  {
    id: "26",
    name: "Scarlett Wright",
    age: 24,
    gender: "female",
    matchScore: 92,
    phone: "+12 345 6789 25",
    email: "scarlett.wright@mail.com",
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    bio: "Singer.",
    status: "pending",
  },
  {
    id: "27",
    name: "Henry Scott",
    age: 28,
    gender: "male",
    matchScore: 87,
    phone: "+12 345 6789 26",
    email: "henry.scott@mail.com",
    avatar: "https://randomuser.me/api/portraits/men/27.jpg",
    bio: "Comedian.",
    status: "rejected",
  },
];
