export const Colors = {
  light: {
    primary: "#76CABB",
    blackText: "#000",
    greenText: "#76CABB",
    whiteText: "#FFF",
    redText: "#DB4437",
    background: "#FFF",
    icon: "#000",
    tabIconDefault: "#687076",
    button: "#76CABB",
    track: "#FFE9F1",
    pink:'#ff5862',
    gray:'#E8E6EA',
    recievedMessage:'#FFc4c4',
    sentMessage:'#ffc3d3',
    placeholderText: '#678999',
    backgroundSecondary:'#F5F5F5',
  },
  dark: {
    primary: "#76CABB",
    blackText: "#000",
    greenText: "#76CABB",
    whiteText: "#FFF",
    redText: "#DB4437",
    background: "black",
    icon: "#000",
    tabIconDefault: "#687076",
    button: "#76CABB",
    track: "#FFE9F1",
    pink:'#ff5862',
    gray:'#E8E6EA',
    recievedMessage:'#FFc4c4',
    sentMessage:'#ffc3d3',
    placeholderText: '#678999',
    backgroundSecondary:'black',
  },
};
