import { Borders } from "@/constants/Borders";
import { FontFamily } from "@/constants/FontFamily";
import { FontSize } from "@/constants/FontSize";
import { hp, wp } from "@/utils";
import { StyleSheet } from "react-native";
import { Colors } from "@/constants/Colors";

export default (theme: "dark" | "light") =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.light.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: wp(4),
      paddingTop: hp(6),
      paddingBottom: hp(2),
      backgroundColor: Colors.light.background,
      borderBottomWidth: 1,
      borderBottomColor: Colors.light.gray,
    },
    backButton: {
      width: wp(10),
      height: wp(10),
      borderRadius: wp(5),
      backgroundColor: Colors.light.gray,
      justifyContent: "center",
      alignItems: "center",
    },
    headerTitle: {
      fontSize: FontSize.large,
      fontWeight: "bold",
      color: Colors.light.blackText,
    },
    headerSpacer: {
      width: wp(10),
    },
    scrollContent: {
      paddingBottom: hp(4),
    },
    usersSection: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginVertical: hp(3),
      paddingHorizontal: wp(4),
    },
    userProfile: {
      alignItems: "center",
    },
    userAvatar: {
      width: wp(16),
      height: wp(16),
      borderRadius: wp(8),
      borderWidth: 3,
      borderColor: Colors.light.primary,
      marginBottom: hp(1),
    },
    userName: {
      fontSize: FontSize.medium,
      fontWeight: "600",
      color: Colors.light.blackText,
    },
    connectLine: {
      flex: 1,
      height: 2,
      backgroundColor: Colors.light.gray,
      marginHorizontal: wp(4),
      position: "relative",
    },
    heartIcon: {
      position: "absolute",
      top: -8,
      left: "50%",
      transform: [{ translateX: -8 }],
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: Colors.light.background,
      justifyContent: "center",
      alignItems: "center",
    },
    preferencesCard: {
      backgroundColor: Colors.light.background,
      borderRadius: wp(4),
      padding: wp(4),
      marginHorizontal: wp(4),
      marginBottom: hp(3),
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      borderLeftWidth: 4,
      borderLeftColor: Colors.light.primary,
    },
    preferencesHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: hp(1.5),
    },
    preferencesTitle: {
      fontSize: FontSize.medium,
      fontWeight: "600",
      color: Colors.light.blackText,
      marginLeft: wp(2),
    },
    preferenceRow: {
      flexDirection: "row",
      alignItems: "flex-start",
    },
    preferenceText: {
      fontSize: FontSize.small,
      color: Colors.light.tabIconDefault,
      marginLeft: wp(2),
      flex: 1,
    },
    section: {
      marginBottom: hp(4),
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: hp(1),
    },
    sectionTitle: {
      fontSize: FontSize.large,
      fontWeight: "bold",
      color: Colors.light.blackText,
      marginLeft: wp(2),
    },
    sectionSubtitle: {
      fontSize: FontSize.small,
      color: Colors.light.tabIconDefault,
      marginBottom: hp(2),
    },
    placesGrid: {
      gap: wp(3),
    },
    placeCard: {
      flex: 1,
      backgroundColor: Colors.light.background,
      borderRadius: wp(4),
      padding: wp(4),
      margin: wp(1.5),
      alignItems: "center",
      borderWidth: 2,
      borderColor: Colors.light.gray,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
      position: "relative",
    },
    placeCardSelected: {
      borderColor: Colors.light.primary,
      backgroundColor: Colors.light.gray,
    },
    placeCardMutual: {
      borderColor: Colors.light.pink,
      backgroundColor: Colors.light.gray,
    },
    placeIconContainer: {
      width: wp(12),
      height: wp(12),
      borderRadius: wp(6),
      backgroundColor: Colors.light.gray,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: hp(1),
    },
    placeIconSelected: {
      backgroundColor: Colors.light.primary,
    },
    placeIconMutual: {
      backgroundColor: Colors.light.pink,
    },
    placeText: {
      fontSize: FontSize.small,
      color: Colors.light.blackText,
      textAlign: "center",
      fontFamily: FontFamily.regular,
    },
    placeTextSelected: {
      color: Colors.light.primary,
      fontFamily: FontFamily.semiBold,
    },
    mutualBadge: {
      position: "absolute",
      top: -wp(1),
      right: -wp(1),
      width: wp(5),
      height: wp(5),
      borderRadius: wp(2.5),
      backgroundColor: Colors.light.pink,
      justifyContent: "center",
      alignItems: "center",
    },
    mutualBadge2: {
      position: "absolute",
      top: -wp(1),
      right: wp(39),
      width: wp(5),
      height: wp(5),
      borderRadius: wp(2.5),
      backgroundColor: Colors.light.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    addDateButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: Colors.light.background,
      borderWidth: 2,
      borderColor: Colors.light.primary,
      borderStyle: "dashed",
      borderRadius: wp(4),
      padding: wp(4),
      justifyContent: "center",
      marginBottom: hp(2),
    },
    addDateText: {
      fontSize: FontSize.medium,
      color: Colors.light.primary,
      fontFamily: FontFamily.semiBold,
      marginLeft: wp(2),
    },
    selectedDatesContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: wp(2),
    },
    dateChip: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: Colors.light.primary,
      paddingHorizontal: wp(3),
      paddingVertical: hp(1),
      borderRadius: wp(5),
      gap: wp(2),
      marginTop: wp(2),
    },
    dateChipText: {
      fontSize: FontSize.small,
      color: Colors.light.whiteText,
      fontFamily: FontFamily.semiBold,
    },
    timeSlotsGrid: {
      gap: wp(2),
    },
    timeSlot: {
      flex: 1,
      backgroundColor: Colors.light.background,
      borderWidth: 1,
      borderColor: Colors.light.gray,
      borderRadius: wp(3),
      paddingVertical: hp(1.5),
      margin: wp(1),
      alignItems: "center",
      position: "relative",
    },
    timeSlotSelected: {
      backgroundColor: Colors.light.primary,
      borderColor: Colors.light.primary,
    },
    timeSlotMutual: {
      borderColor: Colors.light.pink,
      backgroundColor: Colors.light.pink + "10",
    },
    timeText: {
      fontSize: FontSize.small,
      color: Colors.light.blackText,
      fontFamily: FontFamily.semiBold,
    },
    timeTextSelected: {
      color: Colors.light.blackText,
      fontFamily: FontFamily.semiBold,
    },
    mutualIndicator: {
      position: "absolute",
      top: -wp(1),
      right: -wp(1),
      width: wp(4),
      height: wp(4),
      borderRadius: wp(2),
      backgroundColor: Colors.light.background,
      justifyContent: "center",
      alignItems: "center",
    },
    mutualIndicator2: {
      position: "absolute",
      top: -wp(1),
      right: wp(25),
      width: wp(4),
      height: wp(4),
      borderRadius: wp(2),
      backgroundColor: Colors.light.background,
      justifyContent: "center",
      alignItems: "center",
    },
    submitButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: Colors.light.primary,
      paddingVertical: hp(2),
      borderRadius: wp(4),
      marginTop: hp(2),
      gap: wp(2),
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
    submitButtonDisabled: {
      backgroundColor: Colors.light.tabIconDefault,
    },
    submitButtonText: {
      fontSize: FontSize.medium,
      color: Colors.light.whiteText,
      fontFamily: FontFamily.bold,
    },
    loadingContainer: {
      // flexDirection: "row",
      alignItems: "center",
      gap: wp(2),
      justifyContent: "center",
    },
    rejectButton: {
      backgroundColor: Colors.light.pink,
      paddingVertical: hp(1.5),
      paddingHorizontal: wp(10),
      alignSelf: "center",
      marginTop: hp(2),
      borderRadius: Borders.radius1,
    },

    ejectBtnText: {
      color: Colors.light.whiteText,
      fontFamily: FontFamily.bold,
    },

    rejectionBanner: {
      backgroundColor: Colors.light.background,
      padding: hp(2),
      borderRadius: wp(2),
      margin: wp(4),
      borderLeftWidth: wp(1),
    },
    rejectionText: {
      color: Colors.light.pink,
      fontFamily: FontFamily.bold,
      marginBottom: hp(1),
    },
    rejectionDetail: {
      color: Colors.light.tabIconDefault,
      fontSize: FontSize.small,
      marginTop: hp(0.5),
    },
    preferenceCategory: {
      marginBottom: hp(1.5),
      borderBottomWidth: 1,
      borderBottomColor: Colors.light.primary,
      paddingBottom: hp(1),
    },
    categoryRejectButton: {
      alignSelf: "flex-end",
      padding: wp(1.5),
      marginTop: hp(0.5),
    },
    categoryRejectText: {
      color: Colors.light.pink,
      fontSize: FontSize.small,
      fontFamily: FontFamily.medium,
    },
    rejectModalContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1000,
    },
    rejectModalContent: {
      backgroundColor: Colors.light.whiteText,
      width: "80%",
      padding: wp(5),
      borderRadius: Borders.radius2,
    },
    rejectModalTitle: {
      fontSize: FontSize.large,
      fontFamily: FontFamily.bold,
      marginBottom: hp(1.5),
      color: Colors.light.blackText,
    },
    rejectModalSubtitle: {
      fontSize: FontSize.small,
      marginBottom: hp(2),
      color: Colors.light.blackText,
    },
    reasonInput: {
      borderWidth: 1,
      borderColor: Colors.light.gray,
      borderRadius: Borders.radius2,
      padding: wp(3),
      minHeight: hp(12),
      marginBottom: hp(2.5),
      textAlignVertical: "top",
    },
    rejectModalButtons: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: wp(2.5),
    },
    cancelButton: {
      padding: wp(2.5),
    },
    cancelButtonText: {
      color: Colors.light.blackText,
    },
    submitRejectButton: {
      backgroundColor: Colors.light.pink,
      padding: wp(2.5),
      borderRadius: Borders.radius2,
    },
    submitRejectButtonText: {
      color: Colors.light.whiteText,
    },
  });
