import { Borders } from "@/constants/Borders";
import { Colors } from "@/constants/Colors";
import { FontFamily } from "@/constants/FontFamily";
import { FontSize } from "@/constants/FontSize";
import { hp, wp } from "@/utils";
import { Dimensions, StyleSheet } from "react-native";

const { height: SCREEN_HEIGHT } = Dimensions.get("window");
const IMAGE_HEIGHT = hp(60);

export default (theme: "dark" | "light") =>
  StyleSheet.create({
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: Colors[theme].background,
    },
    header: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: hp(2),
      position: "absolute",
      top: hp(1),
      left: 0,
      right: 0,
      zIndex: 20,
      paddingHorizontal: wp(4),
    },
    headerIconContainer: {
      flexDirection: "row",
      gap: wp(2),
    },
    titleContainer: {
      flexDirection: "row",
      marginBottom: hp(2),
      alignItems: "center",
      justifyContent: "space-between",
    },
    titleText: {
      fontFamily: FontFamily.bold,
      color: Colors[theme].greenText,
      fontSize: FontSize.extraLarge,
    },
    headerButton: {
      width: wp(12),
      height: wp(12),
      borderRadius: Borders.circle,
      backgroundColor: "rgba(255,255,255,0.9)",
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    imageContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: IMAGE_HEIGHT,
      zIndex: 1,
    },
    mainImage: {
      width: "100%",
      height: "100%",
      borderBottomLeftRadius: wp(6),
      borderBottomRightRadius: wp(6),
    },
    floatingActionButtons: {
      position: "absolute",
      top: hp(47),
      left: 0,
      right: 0,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: wp(6),
      zIndex: 15,
    },
    actionButton: {
      width: wp(16),
      height: wp(16),
      borderRadius: Borders.circle,
      backgroundColor: "rgba(255,255,255,0.95)",
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 8,
    },
    likeButton: {
      backgroundColor: Colors[theme].redText,
      width: wp(20),
      height: wp(20),
      borderRadius: Borders.circle,
    },
    scrollView: {
      flex: 1,
      zIndex: 10,
    },

    imageSpacer: {
      height: IMAGE_HEIGHT - hp(8),
    },
    contentContainer: {
      backgroundColor: Colors[theme].background,
      borderTopLeftRadius: wp(6),
      borderTopRightRadius: wp(6),
      paddingTop: hp(6),
      minHeight: SCREEN_HEIGHT - IMAGE_HEIGHT + hp(8),
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
      paddingHorizontal: wp(4),
    },
    profileInfo: {
      paddingHorizontal: wp(4),
      marginBottom: hp(2),
      flexDirection: "row",
      justifyContent: "space-between",
    },
    nameContainer: {
      justifyContent: "space-between",

      marginBottom: hp(0.5),
    },
    name: {
      fontSize: FontSize.extraLarge,
      fontFamily: FontFamily.bold,
      color: Colors[theme].blackText,
    },
    sendButton: {
      padding: wp(2),
    },
    profession: {
      fontSize: FontSize.small,
      textTransform: "uppercase",
    },
    section: {
      paddingHorizontal: wp(4),
      marginBottom: hp(3),
    },
    sectionTitle: {
      fontSize: FontSize.large,
      fontFamily: FontFamily.bold,
      color: Colors[theme].blackText,
      marginBottom: hp(1),
    },
    bio: {
      fontSize: FontSize.small,
      color: Colors[theme].blackText,
      lineHeight: 24,
    },
    locationContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: hp(0.5),
    },
    distance: {
      fontSize: FontSize.regular,
      color: Colors[theme].redText,
      marginLeft: wp(1),
    },
    location: {
      fontSize: FontSize.small,
      color: Colors[theme].blackText,
    },
    about: {
      fontSize: FontSize.small,
      color: Colors[theme].blackText,
      lineHeight: 24,
      marginBottom: hp(1),
    },
    readMore: {
      fontSize: FontSize.small,
      color: Colors[theme].redText,
      fontFamily: FontFamily.semiBold,
    },
    interestsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: wp(2),
    },
    galleryHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: hp(2),
    },
    seeAll: {
      fontSize: FontSize.small,
      color: Colors[theme].redText,
      fontFamily: FontFamily.semiBold,
    },
    gallery: {
      gap: wp(2),
    },
    galleryRow: {
      flexDirection: "row",
      gap: wp(2),
      marginBottom: wp(2),
    },
    largeGalleryItem: {
      flex: 1,
      height: hp(25),
      width: wp(38),
      marginRight: wp(2),
      borderRadius: Borders.radius2,
      overflow: "hidden",
      position: "relative",
    },
    smallGalleryItem: {
      flex: 1,
      height: hp(12),
      width: wp(38),
      marginRight: wp(2),
      borderRadius: Borders.radius2,
      overflow: "hidden",
    },
    galleryImage: {
      width: "100%",
      height: "100%",
    },
    playButton: {
      position: "absolute",
      top: wp(2),
      left: wp(2),
      width: wp(8),
      height: wp(8),
      borderRadius: Borders.circle,
      backgroundColor: Colors[theme].redText,
      justifyContent: "center",
      alignItems: "center",
    },

    //modal
    modalBackground: {
      backgroundColor: Colors[theme].whiteText,
      padding: wp(2),
    },
    closeButton: {
      backgroundColor: Colors[theme].whiteText,
      borderRadius: Borders.radius1,
      width: wp(10),
      height: wp(10),
      borderWidth: 1,
      borderColor: Colors[theme].gray,
      marginHorizontal: wp(4),
      marginVertical: hp(2),
      alignItems: "center",
      justifyContent: "center",
    },
    modalImageContainer: {
      justifyContent: "center",
      alignItems: "center",
      width: wp(100),
      backgroundColor: Colors[theme].whiteText,
      height: hp(70),
      marginBottom: hp(2),
      alignSelf: "center",
    },
    modalMainImage: {
      height: hp(75),
      width: "80%",
      alignSelf: "center",
    },
    thumbnailList: {
      paddingHorizontal: wp(2),
      alignItems: "center",
      height: hp(20),
      justifyContent: "center",
    },
    thumbnail: {
      width: wp(18),
      height: wp(18),
      borderRadius: Borders.radius2,
      marginHorizontal: wp(1),
      borderWidth: 2,
      borderColor: "transparent",
      marginBottom: hp(2),
    },
    selectedThumbnail: {
      borderColor: Colors[theme].pink,
    },
    editModalContainer: {
      backgroundColor: Colors[theme].background,
      padding: wp(4),
      borderRadius: Borders.radius2,
    },
    editProfileButton: {
      width: wp(70),
      marginTop: hp(3),
    },
    reelItem: {
      width: wp(70),
      height: hp(20),
      borderRadius: Borders.radius2,
      overflow: "hidden",
      position: "relative",
      marginRight: wp(2),
    },
    video: {
      height: hp(75),
      width: "95%",
      alignSelf: "center",
      borderRadius: Borders.radius2,
      overflow: "hidden",
    },
    reelButton: {
      flex: 0.48,
    },
    cancelButton: {
      backgroundColor: Colors[theme].tabIconDefault,
    },
    reelUploadModal: {
      backgroundColor: Colors[theme].background,
      borderRadius: Borders.radius2,
    },
    reelTopLeftButton: {
      position: "absolute",
      top: hp(1),
      left: wp(2),
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 10,
      padding: wp(2),
      borderRadius: Borders.circle,
    },
    reelTopRightButton: {
      position: "absolute",
      top: hp(1),
      right: wp(2),
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 10,
      padding: wp(2),
      borderRadius: Borders.circle,
    },
    reelCenterPlayButton: {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: [{ translateX: -10 }, { translateY: -10 }],
      backgroundColor: "rgba(0,0,0,0.6)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 5,
      padding: wp(2),
      borderRadius: Borders.circle,
    },
    deleteModalContainer: {
      backgroundColor: Colors[theme].background,
      padding: wp(4),
      borderRadius: Borders.radius2,
    },
    deleteModalText: {
      fontSize: FontSize.regular,
      marginVertical: hp(2),
      textAlign: "center",
    },
    deleteModalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: wp(3),
    },
  });
